api/urls.py
from django.urls import path
from .views import PantryItemViewSet # UserRegisterViewSet
from rest_framework.routers import DefaultRouter


# router = routers.DefaultRouter()
router = DefaultRouter()
router.register('', PantryItemViewSet, basename='pantry-items')
# router.register('User', UserViewSet, basename='users')
# router.register('PantryItem', views.PantryItemViewSet, basename='pantry-items')

urlpatterns = router.urls

pantry_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('pantry_trackr.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('login/', views.LoginView.as_view(), name='login'),
    # path('add-item/', views.AddItemView.as_view(), name='add-item'),
    path('add-item/', views.addItem, name='add-item'),
    # path('my-pantry/', views.MyPantryView.as_view(), name='my-pantry'),
    path('my-pantry/', views.myPantry, name='my-pantry'),
    path('used-item/', views.UsedItemView.as_view(), name='used-item'),
    # path('shopping-list/', views.ShoppingListView.as_view(), name='shopping-list'),

    path('logout/', views.logout_view, name='logout'),
]

templates/add-item.html
{% extends "base.html" %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add An Item</title>
</head>
<body>
  <h1>Create Pantry or Add An Item</h1>
  <!-- optional add photo button? -->
  <input type="text" placeholder="add an item to your pantry">
  <input type="number" placeholder="minimum quantity to always have stored">
  <button>submit to pantry</button>
  <!-- store this info in "My Pantry" -->
</body>
</html> {% endcomment %}



{% comment %} {% extends 'pantry_trackr/base.html' %}
{% block title %}
Add An Item
{% endblock %} {% endcomment %}
 
{% block content %}
<body>
	<div class="body">
		<h3>Create Pantry or Add An Item</h3>
		<br>
		<form method="post" action="{% url 'users:my-pantry' %}">
			{% csrf_token %}
			<div>
				<input class="input-box" id="item_name" name="item_name" type="text" placeholder="item to add to pantry">
				<br><br>
				<input class="input-box" id="quantity_min" name="quantity_min" type="text" placeholder="minimum quantity to always have in pantry"><br><br>
				<input class="input-box" id="quantity_now" name="quantity_now" type="text" placeholder="current quantity in your pantry now"><br><br>
				<button type="submit">submit to pantry</button>
				{% comment %} {{form.name}} {% endcomment %}
			</div>
		</form>
	</div>
</body>
{% endblock %}


{% comment %} submit input to 'My Pantry' {% endcomment %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}Pantry Trackr{% endblock %}</title>
</head>
<body>
    <div class="header">
        <h1 class="app-name">Pantry Trackr</h1>
    </div>
    <ul class="nav-top">
        <li><a href="{% url 'users:home' %}">Home</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'users:my-pantry' %}">My Pantry</a></li>
        <li><a href="{% url 'users:add-item' %}">Add Item To Pantry</a></li>
        {% comment %} <li><a href="{% url 'users:used-item' %}">Used A Pantry Item</a></li>
        <li><a href="{% url 'users:shopping-list' %}">My Shopping List</a></li> {% endcomment %}
        <li><a href="{% url 'users:logout' %}">Logout, <em>{{ user.username }}</em></a></li>
        {% endif %}
    </ul>
    
	{% block content %}
	{% endblock content %}
    </div>

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<body>
    <div>
        {% if user.is_authenticated %}
        <h2>Welcome, <em>{{ user.username }}</em></h2>
        {% comment %} <p><a href="{% url 'logout' %}">logout</a><p> {% endcomment %}
        
        {% else %}
        <h2>Welcome</h2>
        <p>You are not logged in. Please <strong><a href="{% url 'users:login' %}">login</a></strong> or <strong><a href="{% url 'users:signup' %}">sign up</a></strong>.</p>
        {% endif %}
    </div>
</body>
{% endblock %}


{% comment %} user
user.username
url logout
url login {% endcomment %}

templates/login.html
{% extends "base.html" %}

{% block content %}
  <h2>Login</h2>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">login</button>
  </form>
{% endblock content %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="styles.css"/>
  <title>Login</title>
</head>
<body>
  <h1>Welcome!</h1>
  <h3>Login</h3>
  <form action="">
    <input type="email" placeholder="email">
    <input type="password" placeholder="password">
    <button>login</button>
    <!-- need JS for button to submit -->
  </form>
  <br>
  <a href=""></a>
</body>
</html> {% endcomment %}

templates/my-pantry.html
{% extends "base.html" %}


  {% comment %} <div>
    output of add-item including item name and minimum quantity
    include current quantity in pantry
    item name, num currently in pantry, num needed
  </div> {% endcomment %}


{% block title %}
My Pantry
{% endblock %}

{% block content %}
<body>
  <div class="body">
    <h2>My Pantry</h2>
    {% comment %} <form method="post" action="">
      <h3>Add An Item</h3>
			{% csrf_token %}
			<div>
				<input class="input-box" id="item_name" name="item_name" type="text" placeholder="item to add to pantry">
				<br><br>
				<input class="input-box" id="quantity_min" name="quantity_min" type="text" placeholder="minimum quantity to always have in pantry"><br><br>
				<input class="input-box" id="quantity_now" name="quantity_now" type="text" placeholder="current quantity in your pantry now"><br><br>
				<button type="submit">submit to pantry</button>
			</div>
		</form>
    <br><br> {% endcomment %}

    <div>
      {% for item in items %}
        
        <p><strong>Pantry Item:</strong> {{ item.item_name }}</p>
        <p><strong>Minimum Quantity:</strong> {{ item.quantity_min }}</p>
        <p><strong>Current Quantity:</strong> {{ item.quantity_now }}</p>
      {% endfor %}
    </div>


    {% comment %} <form method="post" action="">
      {% csrf_token %}
      <input type="number" value="0" id="input"/> {% endcomment %}
      {% comment %} value is input of quantity min OR currently have in My Pantry {% endcomment %}
      {% comment %} <button id="subtract">-</button>
    </form> {% endcomment %}

    {% comment %} <h1>{{ls.name}}</h1> {% endcomment %}
    {% comment %} {% if object_list %} {% endcomment %}
      {% comment %} <p>{% for item in object_list %}</p>
        <p>{{ item.name }}</p> {% endcomment %}
        {% comment %} {% if photo %}
        {% else %}
        {% endif %}
        <p>photo</p> {% endcomment %}
    {% comment %} {% else %}
      <p><strong>Nothing has been added to your Pantry.</strong> <em>Add an item <a href="add-item.html">here</a>.</em></p> {% endcomment %}
      {% comment %} {% endfor %} {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
  </div>
</body>

<script>
  {% comment %} if (current_input == quantity_min) {
    output that item to 'shopping-list.html'
  } {% endcomment %}

  let input = document.getElementById("input")
  let btn = document.getElementById("subtract")

  btn.addEventListener('click', event => {
    event.preventDefault();
    const currentValue = Number(inputField.value) || 0;
    inputField.value = currentValue - 1;
  });
</script>
{% endblock %}

templates/shopping-list.html
{% extends "base.html" %}

{% block content %}
<body>
  <div class="body">
    <h1>Shopping List</h1>
    <h4><em>When you have notified Pantry Trackr that you have used an item, if that item is at or below its minimum quantity, that item will be automatically added to 'Shopping List' so you can pull the list up when you are shopping without planning ahead.</em></h4>
    <div id="shop-list">
      output when quantity minimum has hit, auto output here
    </div>
  </div>
</body>
{% endblock %}

templates/signup.html
{% block content %}
  <h2>Account Registration</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">register</button>
  </form>
{% endblock %} {% endcomment %}

templates/used-item.html
{% extends "base.html" %}

{% block content %}
<body>
  <div class="body">
    <h2>Used A Pantry Item</h2>
    <form method="post" action="">
      {% csrf_token %}
      <input type="number" value="0" id="input"/>
      {% comment %} value=input of quantity min OR currently have in My Pantry {% endcomment %}
      <button id="subtract">-</button>
    </form>
  </div>
</body>

<script>
  let input = document.getElementById("input")
  let btn = document.getElementById("subtract")

  btn.addEventListener('click', event => {
    event.preventDefault();
    const currentValue = Number(inputField.value) || 0;
    inputField.value = currentValue - 1;
  });
</script>
{% endblock %}